services:
  postgresql:
    image: postgres:16.3
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql-volume/data
    volumes:
      - postgresql:/var/lib/postgresql-volume
      - ./ddl.sh:/docker-entrypoint-initdb.d/ddl.sh
  server:
    image: node:16-alpine
    command: /bin/sh -c "cd app && npm run dev"
    ports:
      - 3000:3000
    volumes:
      - ./:/app
volumes:
  postgresql: